#%RAML 1.0
---
title: Multiple methods
version: 1.0

annotationTypes:
  group:
    type: object
    properties:
      name: string
      description: string

/endpoint1:
    get:
      description: 1
      displayName: 1

/endpoint2:
  (group):
    name: group 1
    description: Manage something 1

    get:
      description: 2
      displayName: 2

/endpoint3:
    get:
      description: 3
      displayName: 3

/endpoint4:
  (group):
    name: group 2
    description: Manage something 2
    get:
      description: 4
      displayName: 4
