#%RAML 1.0
---
title: Multiple methods
version: 1.0

annotationTypes:
  group:
    type: object
    properties:
      name: string
      description: string

/endpoint1:
  /sub1:
    (group):
      name: group 1
      description: Manage something 1
    get:
      description: 1
      displayName: 1
  /sub2:
    get:
      description: 2
      displayName: 2
