#%RAML 1.0
---
title: Multiple methods
version: 1.0

/endpoint1:
    get:
      description: 1
      displayName: 1

    post:
      description: 1b
      displayName: 1b

/endpoint2:
    get:
      description: 2
      displayName: 2

    post:
      description: 2b
      displayName: 2b
