#%RAML 1.0
---
title: Single method
version: 1.0

traits:
  acceptHeader:
    headers:
      Accept:
        description: Specifies the response format
        type: string
        required: true
        example: application/vnd.hmrc.1.0+json

/my/endpoint:
    get:
      description: My description
      displayName: My endpoint
      is: [acceptHeader]
      responses:
        200:
          description: When it works
          body:
            application/json:
              example: |
                { "message": "good" }
        404:
          body:
            application/json:
              example: |
                { "message": "bad" }
