#%RAML 1.0
---
title: With json schama
version: 1.0

/my/endpoint:
    post:
      description: 
      displayName: 
      body:
        application/json:
          type: |
            { "$schema": "http://json-schema.org/schema",
              "type": "object",
              "description": "reference schema details",
              "properties": {
                "my-id": { "$ref": "reference-schema.json#/definitions/my-id" }
              },
              "required": [ "id", "name" ]
            }

