#%RAML 1.0
---
title: With json schama
version: 1.0

/my/endpoint:
    post:
      description: 
      displayName: 
      body:
        application/json:
          type: |
            { "$schema": "http://json-schema.org/schema",
                "type": "object",
                "description": "Schema details",
                "properties": {
                  "id": { "type": "integer" },
                  "name": { "type": "string" },
                  "ownerName": { "type": "string" }
                },
                "required": [ "id", "name" ]
            }
