#%RAML 1.0
---
title: With json schama
version: 1.0

/my/endpoint:
    post:
      description: 
      displayName: 
      body:
        application/json:
          type: !include my-included-schema.json
