#%RAML 1.0
---

title: Test RAML File
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/includedDoc1.md

uses:
  headers: headersWithUses.raml
  errors: errorsWithUses.raml
  queryParameters: queryParameters.raml

types:
  identifier:
    type: string
    pattern: ^[A-Z][0-9]{6}$
    example: A000001